<?php
/**
  * Generated by Exakat 2.1.6 (Build 1091)
  * On 2020-08-26T06:16:33+00:00
  * See https://www.exakat.io/
  */

namespace  {
}

namespace think {
}

namespace app\index\controller {
    class Index {
        public function index() {}
        public function hello($name = 'ThinkPHP5') {}
    }

}

?>
