<?php
/**
  * Generated by Exakat 2.1.6 (Build 1091)
  * On 2020-08-26T06:16:18+00:00
  * See https://www.exakat.io/
  */

namespace  {
}

namespace app {
    /**
     * 应用异常处理类
     */
    class ExceptionHandle extends \think\exception\handle {
        /**
         * 不需要记录信息（日志）的异常类列表
         * @var array
         */
        protected $ignoreReport;

        public function report(Throwable $exception) : void {}
        public function render($request, Throwable $e) : Response {}
    }

    class Request extends \think\request {}

    /**
     * 控制器基础类
     */
    abstract class BaseController {
        /**
         * Request实例
         * @var \think\Request
         */
        protected $request;
        /**
         * 应用实例
         * @var \think\App
         */
        protected $app;
        /**
         * 是否批量验证
         * @var bool
         */
        protected $batchValidate;
        /**
         * 控制器中间件
         * @var array
         */
        protected $middleware;

        public function __construct(App $app) {}
        protected function initialize() {}
        protected function validate(array $data, $validate, array $message = [ ], bool $batch = false) {}
    }

}

namespace app\controller {
    class Index extends \app\basecontroller {
        public function index() {}
        public function hello($name = 'ThinkPHP6') {}
    }

}

namespace think {
}

?>
