<?php
/**
  * Generated by Exakat 2.2.0 (Build 1167)
  * On 2020-11-07T18:27:12+00:00
  * See https://www.exakat.io/
  */

namespace  {
    define('VENDOR_PATH', 'vendor');
    define('OB_HOST_STATS', 1);
    define('OB_SYS_CACHE', 2);
    define('OB_USER_CACHE', 3);
    define('OB_SYS_CACHE_DIR', 4);
    define('OB_VERSION_CHECK', 9);

    /**
     * @package Debug
     */
    function p($src, $Type = 'LOG') {}
    /**
     * @internal
     */
    function _pArray($src, $indent = '') {}
    /**
     * @package Debug
     */
    function d($src) {}
    /**
     * @package Debug
     */
    function pHex($s) {}
    function is_instance_of($sub, $super) {}
    /**
     * Basic translated string
     *
     * More information: https://github.com/vivid-planet/koala-framework/wiki/Translation
     *
     * @param string translated string
     * @param string|string[] string will be replaced with {0} in translated string, array with their {index}
     * @package Trl
     */
    function trl($string, $text = array( )) {}
    /**
     * Translated string in a context
     *
     * @param string Context describing usage of translated string
     * @param string translated string
     * @param string|string[] string will be replaced with {0} in translated string, array with their {index}
     * @package Trl
     */
    function trlc($context, $string, $text = array( )) {}
    /**
     * Translated string in singular/plural form
     *
     * @param string singular form
     * @param string plural form including {0}
     * @param string|string[] string will be replaced with {0} in translated string, array with their {index}
     * @package Trl
     */
    function trlp($single, $plural, $text = array( )) {}
    /**
     * Translated string in singular/plural form in a context
     *
     * @param string Context describing usage of translated string
     * @param string singular form
     * @param string plural form including {0}
     * @param string|string[] string will be replaced with {0} in translated string, array with their {index}
     * @package Trl
     */
    function trlcp($context, $single, $plural, $text = array( )) {}
    /**
     * @see trl
     * @package Trl
     */
    function trlKwf($string, $text = array( )) {}
    /**
     * @see trlc
     * @package Trl
     */
    function trlcKwf($context, $string, $text = array( )) {}
    /**
     * @see trlp
     * @package Trl
     */
    function trlpKwf($single, $plural, $text = array( )) {}
    /**
     * @see trlcp
     * @package Trl
     */
    function trlcpKwf($context, $single, $plural, $text = array( )) {}
    /**
     * @see trl
     * @package Trl
     */
    function trlStatic($string, $text = array( )) {}
    /**
     * @see trlc
     * @package Trl
     */
    function trlcStatic($context, $string, $text = array( )) {}
    /**
     * @see trlp
     * @package Trl
     */
    function trlpStatic($single, $plural, $text = array( )) {}
    /**
     * @see trlcp
     * @package Trl
     */
    function trlcpStatic($context, $single, $plural, $text = array( )) {}
    /**
     * @see trl
     * @package Trl
     */
    function trlKwfStatic($string, $text = array( )) {}
    /**
     * @see trlc
     * @package Trl
     */
    function trlcKwfStatic($context, $string, $text = array( )) {}
    /**
     * @see trlp
     * @package Trl
     */
    function trlpKwfStatic($single, $plural, $text = array( )) {}
    /**
     * @see trlcp
     * @package Trl
     */
    function trlcpKwfStatic($context, $single, $plural, $text = array( )) {}
    function defaults($d, $v) {}
    function duration($ts) {}
    function graphics_avail() {}
    function fill_arc($im, $centerX, $centerY, $diameter, $start, $end, $color1, $color2, $text = '', $placeindex = 0) {}
    function text_arc($im, $centerX, $centerY, $diameter, $start, $end, $color1, $text, $placeindex = 0) {}
    function fill_box($im, $x, $y, $w, $h, $color1, $color2, $text = '', $placeindex = '') {}
    function bsize($s) {}
    function sortheader($key, $name, $extra = '') {}
    function menu_entry($ob, $title) {}
    function put_login_link($s = "Login") {}
}


















?>
