<?php
/**
  * Generated by Exakat 2.1.6 (Build 1091)
  * On 2020-08-26T06:16:46+00:00
  * See https://www.exakat.io/
  */

namespace  {
}

namespace app\index\controller {
    class Index {
        public function index() {}
    }

}

?>
