<?php
/**
  * Generated by Exakat 2.2.0 (Build 1167)
  * On 2020-11-07T18:17:59+00:00
  * See https://www.exakat.io/
  */

namespace  {
    /**
     * Marks a variable as being safe.
     *
     * @param string $string A PHP variable
     *
     * @return string
     */
    function twig_raw_filter($string) {}
    function twig_var_dump(Twig_Environment $env, $context, $vars) {}
    /**
     * Loads a template from a string.
     *
     * <pre>
     * {{ include(template_from_string("Hello {{ name }}")) }}
     * </pre>
     *
     * @param Twig_Environment $env      A Twig_Environment instance
     * @param string           $template A template as a string or object implementing __toString()
     *
     * @return Twig_Template
     */
    function twig_template_from_string(Twig_Environment $env, $template) {}
    /**
     * Cycles over a value.
     *
     * @param ArrayAccess|array $values
     * @param int               $position The cycle position
     *
     * @return string The next value in the cycle
     */
    function twig_cycle($values, $position) {}
    /**
     * Returns a random value depending on the supplied parameter type:
     * - a random item from a Traversable or array
     * - a random character from a string
     * - a random integer between 0 and the integer parameter.
     *
     * @param Twig_Environment                   $env
     * @param Traversable|array|int|float|string $values The values to pick a random item from
     *
     * @throws Twig_Error_Runtime when $values is an empty array (does not apply to an empty string which is returned as is)
     *
     * @return mixed A random value from the given sequence
     */
    function twig_random(Twig_Environment $env, $values = null) {}
    /**
     * Converts a date to the given format.
     *
     * <pre>
     *   {{ post.published_at|date("m/d/Y") }}
     * </pre>
     *
     * @param Twig_Environment                      $env
     * @param DateTimeInterface|DateInterval|string $date     A date
     * @param string|null                           $format   The target format, null to use the default
     * @param DateTimeZone|string|null|false        $timezone The target timezone, null to use the default, false to leave unchanged
     *
     * @return string The formatted date
     */
    function twig_date_format_filter(Twig_Environment $env, $date, $format = null, $timezone = null) {}
    /**
     * Returns a new date object modified.
     *
     * <pre>
     *   {{ post.published_at|date_modify("-1day")|date("m/d/Y") }}
     * </pre>
     *
     * @param Twig_Environment         $env
     * @param DateTimeInterface|string $date     A date
     * @param string                   $modifier A modifier string
     *
     * @return DateTimeInterface A new date object
     */
    function twig_date_modify_filter(Twig_Environment $env, $date, $modifier) {}
    /**
     * Converts an input to a DateTime instance.
     *
     * <pre>
     *    {% if date(user.created_at) < date('+2days') %}
     *      {# do something #}
     *    {% endif %}
     * </pre>
     *
     * @param Twig_Environment               $env
     * @param DateTimeInterface|string|null  $date     A date or null to use the current time
     * @param DateTimeZone|string|null|false $timezone The target timezone, null to use the default, false to leave unchanged
     *
     * @return DateTime A DateTime instance
     */
    function twig_date_converter(Twig_Environment $env, $date = null, $timezone = null) {}
    /**
     * Replaces strings within a string.
     *
     * @param string            $str  String to replace in
     * @param array|Traversable $from Replace values
     *
     * @return string
     */
    function twig_replace_filter($str, $from) {}
    /**
     * Rounds a number.
     *
     * @param int|float $value     The value to round
     * @param int|float $precision The rounding precision
     * @param string    $method    The method to use for rounding
     *
     * @return int|float The rounded number
     */
    function twig_round($value, $precision = 0, $method = 'common') {}
    /**
     * Number format filter.
     *
     * All of the formatting options can be left null, in that case the defaults will
     * be used.  Supplying any of the parameters will override the defaults set in the
     * environment object.
     *
     * @param Twig_Environment $env
     * @param mixed            $number       A float/int/string of the number to format
     * @param int              $decimal      the number of decimal points to display
     * @param string           $decimalPoint the character(s) to use for the decimal point
     * @param string           $thousandSep  the character(s) to use for the thousands separator
     *
     * @return string The formatted number
     */
    function twig_number_format_filter(Twig_Environment $env, $number, $decimal = null, $decimalPoint = null, $thousandSep = null) {}
    /**
     * URL encodes (RFC 3986) a string as a path segment or an array as a query string.
     *
     * @param string|array $url A URL or an array of query parameters
     *
     * @return string The URL encoded value
     */
    function twig_urlencode_filter($url) {}
    /**
     * Merges an array with another one.
     *
     * <pre>
     *  {% set items = { 'apple': 'fruit', 'orange': 'fruit' } %}
     *
     *  {% set items = items|merge({ 'peugeot': 'car' }) %}
     *
     *  {# items now contains { 'apple': 'fruit', 'orange': 'fruit', 'peugeot': 'car' } #}
     * </pre>
     *
     * @param array|Traversable $arr1 An array
     * @param array|Traversable $arr2 An array
     *
     * @return array The merged array
     */
    function twig_array_merge($arr1, $arr2) {}
    /**
     * Slices a variable.
     *
     * @param Twig_Environment $env
     * @param mixed            $item         A variable
     * @param int              $start        Start of the slice
     * @param int              $length       Size of the slice
     * @param bool             $preserveKeys Whether to preserve key or not (when the input is an array)
     *
     * @return mixed The sliced variable
     */
    function twig_slice(Twig_Environment $env, $item, $start, $length = null, $preserveKeys = false) {}
    /**
     * Returns the first element of the item.
     *
     * @param Twig_Environment $env
     * @param mixed            $item A variable
     *
     * @return mixed The first element of the item
     */
    function twig_first(Twig_Environment $env, $item) {}
    /**
     * Returns the last element of the item.
     *
     * @param Twig_Environment $env
     * @param mixed            $item A variable
     *
     * @return mixed The last element of the item
     */
    function twig_last(Twig_Environment $env, $item) {}
    /**
     * Joins the values to a string.
     *
     * The separator between elements is an empty string per default, you can define it with the optional parameter.
     *
     * <pre>
     *  {{ [1, 2, 3]|join('|') }}
     *  {# returns 1|2|3 #}
     *
     *  {{ [1, 2, 3]|join }}
     *  {# returns 123 #}
     * </pre>
     *
     * @param array  $value An array
     * @param string $glue  The separator
     *
     * @return string The concatenated string
     */
    function twig_join_filter($value, $glue = '') {}
    /**
     * Splits the string into an array.
     *
     * <pre>
     *  {{ "one,two,three"|split(',') }}
     *  {# returns [one, two, three] #}
     *
     *  {{ "one,two,three,four,five"|split(',', 3) }}
     *  {# returns [one, two, "three,four,five"] #}
     *
     *  {{ "123"|split('') }}
     *  {# returns [1, 2, 3] #}
     *
     *  {{ "aabbcc"|split('', 2) }}
     *  {# returns [aa, bb, cc] #}
     * </pre>
     *
     * @param Twig_Environment $env
     * @param string           $value     A string
     * @param string           $delimiter The delimiter
     * @param int              $limit     The limit
     *
     * @return array The split string as an array
     */
    function twig_split_filter(Twig_Environment $env, $value, $delimiter, $limit = null) {}
    /**
     * @internal
     */
    function _twig_default_filter($value, $default = '') {}
    /**
     * Returns the keys for the given array.
     *
     * It is useful when you want to iterate over the keys of an array:
     *
     * <pre>
     *  {% for key in array|keys %}
     *      {# ... #}
     *  {% endfor %}
     * </pre>
     *
     * @param array $array An array
     *
     * @return array The keys
     */
    function twig_get_array_keys_filter($array) {}
    /**
     * Reverses a variable.
     *
     * @param Twig_Environment         $env
     * @param array|Traversable|string $item         An array, a Traversable instance, or a string
     * @param bool                     $preserveKeys Whether to preserve key or not
     *
     * @return mixed The reversed input
     */
    function twig_reverse_filter(Twig_Environment $env, $item, $preserveKeys = false) {}
    /**
     * Sorts an array.
     *
     * @param array|Traversable $array
     *
     * @return array
     */
    function twig_sort_filter($array) {}
    /**
     * @internal
     */
    function twig_in_filter($value, $compare) {}
    /**
     * Returns a trimmed string.
     *
     * @return string
     *
     * @throws Twig_Error_Runtime When an invalid trimming side is used (not a string or not 'left', 'right', or 'both')
     */
    function twig_trim_filter($string, $characterMask = null, $side = 'both') {}
    /**
     * Escapes a string.
     *
     * @param Twig_Environment $env
     * @param mixed            $string     The value to be escaped
     * @param string           $strategy   The escaping strategy
     * @param string           $charset    The charset
     * @param bool             $autoescape Whether the function is called by the auto-escaping feature (true) or by the developer (false)
     *
     * @return string
     */
    function twig_escape_filter(Twig_Environment $env, $string, $strategy = 'html', $charset = null, $autoescape = false) {}
    /**
     * @internal
     */
    function twig_escape_filter_is_safe(Twig_Node $filterArgs) {}
    function twig_convert_encoding($string, $to, $from) {}
    /**
     * Returns the length of a variable.
     *
     * @param Twig_Environment $env   A Twig_Environment instance
     * @param mixed            $thing A variable
     *
     * @return int The length of the value
     */
    function twig_length_filter(Twig_Environment $env, $thing) {}
    /**
     * Converts a string to uppercase.
     *
     * @param Twig_Environment $env
     * @param string           $string A string
     *
     * @return string The uppercased string
     */
    function twig_upper_filter(Twig_Environment $env, $string) {}
    /**
     * Converts a string to lowercase.
     *
     * @param Twig_Environment $env
     * @param string           $string A string
     *
     * @return string The lowercased string
     */
    function twig_lower_filter(Twig_Environment $env, $string) {}
    /**
     * Returns a titlecased string.
     *
     * @param Twig_Environment $env
     * @param string           $string A string
     *
     * @return string The titlecased string
     */
    function twig_title_string_filter(Twig_Environment $env, $string) {}
    /**
     * Returns a capitalized string.
     *
     * @param Twig_Environment $env
     * @param string           $string A string
     *
     * @return string The capitalized string
     */
    function twig_capitalize_string_filter(Twig_Environment $env, $string) {}
    /**
     * @internal
     */
    function twig_ensure_traversable($seq) {}
    /**
     * Checks if a variable is empty.
     *
     * <pre>
     * {# evaluates to true if the foo variable is null, false, or the empty string #}
     * {% if foo is empty %}
     *     {# ... #}
     * {% endif %}
     * </pre>
     *
     * @param mixed $value A variable
     *
     * @return bool true if the value is empty, false otherwise
     */
    function twig_test_empty($value) {}
    /**
     * Checks if a variable is traversable.
     *
     * <pre>
     * {# evaluates to true if the foo variable is an array or a traversable object #}
     * {% if foo is iterable %}
     *     {# ... #}
     * {% endif %}
     * </pre>
     *
     * @param mixed $value A variable
     *
     * @return bool true if the value is traversable
     */
    function twig_test_iterable($value) {}
    /**
     * Renders a template.
     *
     * @param Twig_Environment $env
     * @param array            $context
     * @param string|array     $template      The template to render or an array of templates to try consecutively
     * @param array            $variables     The variables to pass to the template
     * @param bool             $withContext
     * @param bool             $ignoreMissing Whether to ignore missing templates or not
     * @param bool             $sandboxed     Whether to sandbox the template or not
     *
     * @return string The rendered template
     */
    function twig_include(Twig_Environment $env, $context, $template, $variables = array( ), $withContext = true, $ignoreMissing = false, $sandboxed = false) {}
    /**
     * Returns a template content without rendering it.
     *
     * @param Twig_Environment $env
     * @param string           $name          The template name
     * @param bool             $ignoreMissing Whether to ignore missing templates or not
     *
     * @return string The template source
     */
    function twig_source(Twig_Environment $env, $name, $ignoreMissing = false) {}
    /**
     * Provides the ability to get constants from instances as well as class/global constants.
     *
     * @param string      $constant The name of the constant
     * @param null|object $object   The object to get the constant from
     *
     * @return string
     */
    function twig_constant($constant, $object = null) {}
    /**
     * Checks if a constant exists.
     *
     * @param string      $constant The name of the constant
     * @param null|object $object   The object to get the constant from
     *
     * @return bool
     */
    function twig_constant_is_defined($constant, $object = null) {}
    /**
     * Batches item.
     *
     * @param array $items An array of items
     * @param int   $size  The size of the batch
     * @param mixed $fill  A value used to fill missing items
     *
     * @return array
     */
    function twig_array_batch($items, $size, $fill = null) {}
    /**
     * Returns the attribute value for a given array/object.
     *
     * @param mixed  $object            The object or array from where to get the item
     * @param mixed  $item              The item to get from the array or object
     * @param array  $arguments         An array of arguments to pass if the item is an object method
     * @param string $type              The type of attribute (@see Twig_Template constants)
     * @param bool   $isDefinedTest     Whether this is only a defined check
     * @param bool   $ignoreStrictCheck Whether to ignore the strict attribute check or not
     *
     * @return mixed The attribute value, or a Boolean when $isDefinedTest is true, or null when the attribute is not set and $ignoreStrictCheck is true
     *
     * @throws Twig_Error_Runtime if the attribute does not exist and Twig is running in strict mode and $isDefinedTest is false
     *
     * @internal
     */
    function twig_get_attribute(Twig_Environment $env, Twig_Source $source, $object, $item, array $arguments = array( ), $type = 'any', $isDefinedTest = false, $ignoreStrictCheck = false, $sandboxed = false) {}
}






















?>
